FROM mcr.microsoft.com/mssql-tools

# Install openjdk-8
RUN apt-get update \
    && apt-get install -y openjdk-8-jdk
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64

# Install dev tools
RUN apt-get install -y zip